version: '2'
services:
  academy-api:
    build: .
    environment:
      # PORT: '5000'
      # SHOW_URLS: 'true'
      # COURSES_URL: '192.168.99.101'
      # COURSES_PORT: '3000'
      # COURSES_ENTRY: 'courses-ms/resources/courses'
      PORT: '5000'      
      SHOW_URLS: 'true'
      API_URL: '35.196.126.118'
      BOT_PORT: '3000'
      BOT_ENTRY: 'api/'
      NEWS_URL: '35.231.237.201'
      NEWSLETTER_PORT: '3002'
    ports:
      - '5000:5000'