version: '2'
services:
  academy-api:
    build: .
    environment:
      SHOW_URLS: 'true'
      URL: '35.231.237.201'
      BOT_PORT: '3000'
      BOT_ENTRY: 'api/'
      CENTERS_PORT: '3001'
      CENTERS_ENTRY: 'courses-ms/resources/courses'      
      NEWSLETTER_PORT: '3002'
      USER_PORT: '3003'
      USER_ENTRY: 'api/auth'
      PORT: '5000'            
    ports:
      - '5000:5000'